### ISSUE TITLE
Feature Request - Support for SSO

### ISSUE THREAD

**Issue by BhuviTheDataGuy** [horilla-opensource/horilla#165]
Do you have any support for using Google SSO, so its easy to manage.

**Comment by horilla-opensource** [comment]
Hi @BhuviTheDataGuy ,
Support for SSO is not currently on the roadmap of Horilla.
Since this tool is strictly based on for a single company where the users cannot come in and register directly to become a user in the system. The HR admin is the responsible person for creating the user record in the database.
If we enable the SSO for the system, once the user is logged in to the system, he won't be able to do much things unless the HR admin adds his work data, access rights etc.
Also if hosted, other users will be able to login to the database using the SSO.

We don't think its necessary at this stage to have this implemented.
If wanted we can open a discussion on this topic and have a conversation on this.

With Regards,
**Team Horilla**
