### ISSUE TITLE
Survey not working

### ISSUE THREAD

**Issue by senolsun** [horilla-opensource/horilla#276]
# Bug Report

## Description

Interview survey is not working. 

## Steps to Reproduce

1. Add a new survey
2. Add questions to the survey
3. Link the survey to the new job opening when creating the new job
4. User applies to the new job, survey is not shown, it immediately saves the application and workflow stops.

## Expected Behavior

It is supposed to show the survey after the user submits his application. Actually it'd be nicer if the survey is shown on the actual application page rather than the second page but either way it doesn't show the survey at all.

## Actual Behavior

Application is saved immediately and survey is not  shown.

## Environment

- **Django Version: Latest version
- **Python Version:** 3.12.3
- **Operating System: Windows 11
- **Browser:** Chrome latest

## Priority

High

**Comment by horilla-opensource** [comment]
Hi @senolsun ,
Sorry for the inconvenience caused. The team is looking into the issue and will provide an update asap.

With Regards,
**Team Horilla**

**Comment by senolsun** [comment]
just noticed that if tried from another browser that hasn't logged in as admin, it works.

One other thing I noticed is that it does not ask for a photo to be uploaded when logged in as admin but it does when not logged in, but there is no sign of a photo requirement on the page therefore most applicants are required to fill the form twice.

**Comment by horilla-opensource** [comment]
Hi @senolsun ,
We have checked the issue at our end. Basically as you have told, the survey is a feature which is solely meant for the candidate view and not for the admin levels, as the admins won't be really using the candidate survey form. They'll be using the backend view for the same.
About the submission error of the photo, we will update the fix for it soon.

With Regards,
**Team Horilla**
