### ISSUE TITLE
Documentation Deploy on Cpanel Shared Hosting

### ISSUE THREAD

**Issue by prima-github** [horilla-opensource/horilla#281]
# Feature Request

## Description
Documentation on Deploy on Cpanel Shared Hosting with MySQL database until Horilla is Live on web server 

## Use Case
Deploy on Cpanel Shared Hosting

Do you have any documentation or tutorial how to install it on shared hosting with cpanel web server ?

And tutorial how to update the application ?

**Comment by horilla-opensource** [comment]
Hi @prima-github ,
Refer the doc in the link for installation guide while going to production.
[Horilla Deployment Guide](https://drive.google.com/file/d/1P8-OMH-ST6TQM3n2QDs2LqcgzW-ragUb/view?usp=sharing)

We suggest you to move with PostgreSQL database rather than MySQL because support for MySQL is shortly going to be removed as there are some inconsistencies with the MySQL databases. 

With Regards,
**Team Horilla**

**Comment by prima-github** [comment]
Hy, Can you give permission to access your google drive link ?
Thanks

**Comment by horilla-opensource** [comment]
The permission is updated.
Please check now.
