### ISSUE TITLE
Cannont Delete Employee, Programing Error.

### ISSUE THREAD

**Issue by MrcellSbst** [horilla-opensource/horilla#287]
# Bug Report

## Description

_[Cannot Delete Employee.]_

## Steps to Reproduce

1. _[Trying to Delete an Employee]_

## Expected Behavior

_[Employee would be gone? deleted? cease to exist?]_

## Actual Behavior

_[Programming Error]_

## Screenshots

_[![image](https://github.com/user-attachments/assets/dcf27b74-20fc-45de-8ed3-a774fe327244)]_

## Environment

- **Django Version:** _[4.2.11]_
- **Python Version:** _[3.10.12]_
- **Operating System:** _[Ubuntu 22.04]_
- **Browser:** _[Brave (chromium based)]_
- **DB.** _[Using PostgreSQL]_

**Comment by horilla-opensource** [comment]
Hi @MrcellSbst ,
May I know whether you are using a fresh database or demo provided in the repo?

With Regards,
**Team Horilla**

**Comment by MrcellSbst** [comment]
fresh database

**Comment by horilla-opensource** [comment]
The issue mentioned above is because of the migration command not being completed successfully. For fresh database, the initial migrations command should add all these columns into the table.
Can you try to run the migrations command for the payroll app explicitly and try again ?

`python3 manage.py migrate payroll`

With Regards,
**Team Horilla**

**Comment by MrcellSbst** [comment]
ok, seems working now. but i can't delete employee that already have att record?

**Comment by horilla-opensource** [comment]
The admin have the access to bypass that. Are you given any error while trying to delete the employee?

**Comment by MrcellSbst** [comment]
![image](https://github.com/user-attachments/assets/3564d1b8-ef86-467c-bbab-b2d977371d22)

**Comment by horilla-opensource** [comment]
It is because of a foreign key constraint of the employee record existing in other models.
You need to filter out the records from the displayed models in the popup and delete it. Just go to the corresponding models view and filter the records with the employees name. 

We know it's a bit tedious task, but this kind of scenario generally doesn't arise where an employee with much data needs to be deleted. In case of deletion required, you'll have to clear out the data from the models.

When an employee resigns, the method we use is to archive the employee as data of the past employees is sometimes needed for future use.

I hope you understand the scenario.

With Regards,
**Team Horilla**
