### ISSUE TITLE
Allow employees to file late dates in leaves

### ISSUE THREAD

**Issue by XConradX** [horilla-opensource/horilla#308]
In leave creation there's no feature allowing the employee for late filing of leaves or how to enable it to allow them to file previous dates. i.e sick leaves are allowed to be filed once they come back to the office.

**Comment by horilla-opensource** [comment]
Hi @XConradX ,
Currently we don't allow employees to file leave requests for previous dates, but the HR admin has the permission to create the leaves for the corresponding employee for past days.
It's relatively more convenient to not allow employees to sent request for past days without prior permissions and if needed only the HR admins are possible to make the requests. This will allow people to sent the request prior to the day they are taking the off rather than after that day.

With Regards,
**Team Horilla**

**Comment by XConradX** [comment]
Thanks Horilla, In our case, we allow to file sick leaves for previous dates. It's a burden to HR or admin if they will file the leaves for the employees. This is for a specific leave only linke sick leaves, but for vacation leave, its a policy to file days before the date of leave. Is there a way that we can allow a specific leave to file from the past days. 
<img width="1153" alt="image" src="https://github.com/user-attachments/assets/e9549724-0eac-4aea-aec5-94ae43f8eabf">

**Comment by horilla-opensource** [comment]
Hi @XConradX ,
We already do have a similar feature to allow past day leave creation for all leave types and not for specific leave type.
You can find the option inside the settings tab. Please check with the demo instance link given below to find the setting.
[https://demo.horilla.com/leave/employee-past-leave-restriction](https://demo.horilla.com/leave/employee-past-leave-restriction)

Please let us know if you have any questions.

With Regards,
**Team Horilla**

**Comment by XConradX** [comment]
Found it. Many thanks Horilla team.
