### ISSUE TITLE
[BUG] Timer issue: Page reload starts timer again at 0:00

### ISSUE THREAD

**Issue by borishinzer** [horilla-opensource/horilla#74]
# Bug Report
If you close the horilla tab or reload the page the timer restarts at 0:00.
Also, although I am clocked-in I get shown as "expected working" in the dashboard.

<img width="1761" alt="Bildschirmfoto 2024-01-05 um 16 16 09" src="https://github.com/horilla-opensource/horilla/assets/10340538/ea87743b-e598-4062-8802-7eced12ae222">

**Comment by horilla-opensource** [comment]
Hi @borishinzer ,
Please check with the latest committed code.
We have added the fix for this yesterday in the commit [ [FIX] ATTENDANCE: Refresh function for fetching attendance time ](https://github.com/horilla-opensource/horilla/commit/09640e6f53b60777693c4921266e16880f47ea10)

I think that'll solve the issue.
Please let us know if the issue still persists after that also.

With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment]
We are checking it from our side.
Could you please try to hard refresh or start a new instance in another browser?
Maybe it might be the issue with an existing issue.
We tried it on different browsers but couldn't really reproduce the issue.
We are testing with different use cases to reproduce it.

**Comment by borishinzer** [comment]
Tested in firefox and incognito mode. As soon I reload the page, the counter (in the check-in button) starts again at 0:00 and I am still "Expected working"

**Comment by horilla-opensource** [comment]
Please try it by removing the attendance and attendance activity for the current day.
Maybe it is an issue with some existing data by which the calculation is getting wrong after the current updates.
Also please make sure that the changes to the database is applied after the latest pull by using the _makemigrations and migrate_ command.

**Comment by borishinzer** [comment]
Punch-out and punch-in fixed the issue (also the "Expected working"). Thank you.
